### ISSUE TITLE
Missing STEP File for extrusor_mini_lever_v7.4

### ISSUE THREAD

**Issue by SnickCH** [ComunidadMaker3D/CM3D-PrusaMini#1]
Missing STEP File for extrusor_mini_lever_v7.4

The mini lever (not the FSlever) 7.4 is missing as a step file. Could you be so kind and upload it?
Thank you very much for your great design. 
Best regards

**Comment by jfestrada** [comment]
Hi @SnickCH, 

You were right, I have uploaded the step file. Thanks!!
